export const gameContexts = [
  {
    contextName: 'Electronics',
    timeInterval: '7 days',
    maxTicketAmount: 200,
    minTiketAmount: 1,
    maxNumberOfPlayers: 500,
    minNumbersOfPlayers: 10,
    ticketPrice: 1,
    id: 0,
  },
  {
    contextName: 'Cars',
    timeInterval: '30 days',
    maxTicketAmount: 1000,
    minTiketAmount: 1,
    maxNumberOfPlayers: 500,
    minNumbersOfPlayers: 10,
    ticketPrice: 2,
    id: 1,
  },
  {
    contextName: 'Houses',
    timeInterval: '60 days',
    maxTicketAmount: 1000,
    minTiketAmount: 1,
    maxNumberOfPlayers: 1000,
    minNumbersOfPlayers: 10,
    ticketPrice: 3,
    id: 2,
  },
];
